# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CalvingFrontMachine
                                 A QGIS plugin
 Generates polygonal calving front/land-ocean vector masks from raster images.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-07-24
        copyright            : (C) 2018 by Daniel Cheng
        email                : dlcheng@uci.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CalvingFrontMachine class from file CalvingFrontMachine.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .calving_front_machine import CalvingFrontMachine
    return CalvingFrontMachine(iface)
